name: mypy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  mypy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: pip install -r requirements.txt

      - name: Run
        run: |
          mypy \
            --explicit-package-bases \
            --ignore-missing-imports \
            --check-untyped-defs \
            .
