name: mypy

on:
  push:

jobs:
  mypy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: pip install -r requirements.txt

      - name: Run
        run: mypy --ignore-missing-imports .
